# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170906_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='question',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='variant',
            name='avg_price_per_cup',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='variant',
            name='avg_retail_price',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='variant',
            name='prep_yield_factor',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size_of_cup_equivalent',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
